# -*- coding: utf-8 -*-
"""Unsing List, dictionarires and matrix on python

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1EyqkUhQPNvucD-7OuSggFPEpPrec7tQV

Exercise 1 - lists
Create a repeating structure to read 5 numbers and store them within an integer. After reading, I yell another repeat structure to sum all the values ​​typed
"""

lista = []
for _ in range(1, 6):
  value = int(input('write a value:'))
  lista.append(value)

len(lista)

sum = 0
for i in range(len(lista)):
  #print(lista[i])
  sum += lista[i]
print('sum:',sum)

import numpy as np
np.array(lista).sum()

"""Exercises 2 - dictionaries
Create a dictionary to store the name and grade of 3 students, reading the values ​​through a repeating structure. Then create a new repeat structure to sum all the grades and return the average
"""

students ={}
for _ in range(1, 4):
  name = input('wwrite a name:  ')
  note = float(input('write a note:  '))
students[name] = note

students

students.values()

sum = 0 
for note in students.values():
  #print(note)
  sum += note 
  print('averege',sum/3)

"""Exercise 3: Matrix
Given the array below, build a repeating structure to loop through and sum all array elements
"""

import numpy as np
np.array(matriz)

matriz =np.array([[3, 4, 1],
                   [3, 1, 5]])
matriz

matriz.shape

sum = 0
for i in range(matriz.shape[0]):
  for j in range(matriz.shape[1]):
    #print([i][j])
    sum += matriz[i][j]
print('sum:',sum)